spring.application.name=auth-service

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/flowforge_auth}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8081

jwt.secret=${JWT_SECRET:flowforge_dev_secret_key_minimum_32_chars_long}
jwt.access-token-expiry=900000
jwt.refresh-token-expiry=604800000
